const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generates a PDF booking slip/bill and returns a path or buffer
 * @param {Object} data Booking or Bill data
 * @param {String} type 'HOTEL', 'DOCTOR', 'BILL'
 * @returns {Promise<String>} Resolves with the file path
 */
exports.generatePDF = (data, type) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            
            // Ensure uploads directory exists
            const uploadsDir = path.join(__dirname, '../../uploads/pdfs');
            if (!fs.existsSync(uploadsDir)) {
                fs.mkdirSync(uploadsDir, { recursive: true });
            }

            const fileName = `${type}_${Date.now()}.pdf`;
            const filePath = path.join(uploadsDir, fileName);
            
            const writeStream = fs.createWriteStream(filePath);
            doc.pipe(writeStream);

            // PDF Header
            doc.fillColor('#f59e0b').fontSize(24).text('APOLLO CONCIERGE', { align: 'center' });
            doc.moveDown();
            
            doc.fillColor('#4b5563').fontSize(12).text(`Official ${type === 'BILL' ? 'Invoice' : 'Reservation Slip'}`, { align: 'center' });
            doc.moveDown(2);

            // PDF Body Content
            doc.fillColor('#111827').fontSize(14).text('Patient / Guest Details:', { underline: true });
            doc.fontSize(12).text(`Name: ${data.patientName || data.name || 'Unknown'}`);
            if (data.phone) doc.text(`Phone: ${data.phone}`);
            doc.moveDown();

            if (type === 'HOTEL') {
                doc.fontSize(14).text('Hotel Property:', { underline: true });
                doc.fontSize(12).text(`Hotel: ${data.hotel}`);
                doc.text(`Room: ${data.roomType}`);
                doc.text(`Check-In: ${data.checkIn}`);
                doc.text(`Check-Out: ${data.checkOut}`);
            } else if (type === 'DOCTOR') {
                doc.fontSize(14).text('Appointment Details:', { underline: true });
                doc.fontSize(12).text(`Doctor: ${data.doctor}`);
                doc.text(`Date: ${data.date}`);
                doc.text(`Time: ${data.time}`);
            } else if (type === 'BILL') {
                doc.fontSize(14).text('Billing Details:', { underline: true });
                doc.fontSize(12).text(`Amount Due: $${data.amount || '0.00'}`);
                doc.text(`Description: ${data.description || 'Medical Services'}`);
            }
            
            doc.moveDown(2);
            doc.fillColor('#9ca3af').fontSize(10).text(`Generated by: ${data.agentName || 'Apollo System'}`, { align: 'right' });
            doc.text(`Ref ID: #REF${Math.floor(Math.random() * 1000000)}`, { align: 'right' });

            doc.end();

            writeStream.on('finish', () => {
                resolve(filePath);
            });
            writeStream.on('error', (err) => {
                reject(err);
            });
        } catch (err) {
            reject(err);
        }
    });
};
